(global-set-key (kbd "C-x w") 'elfeed)

(setq elfeed-feeds
      '(("http://bristolcrypto.blogspot.com/feeds/posts/default" crypto)
				("https://feeds.feedburner.com/AFewThoughtsOnCryptographicEngineering" crypto)
				("https://www.schneier.com/blog/atom.xml" crypto)
				("https://feeds.feedburner.com/GoogleOnlineSecurityBlog" crypto)
				("http://googleprojectzero.blogspot.com/feeds/posts/default" crypto)
				("https://www.lightbluetouchpaper.org/feed/" crypto)
				("https://terrytao.wordpress.com/feed/" math)
				("https://gowers.wordpress.com/feed/" math)
				("https://gilkalai.wordpress.com/feed/" math)
				("https://golem.ph.utexas.edu/category/atom10.xml" math)
				("http://www.springer.com/mathematics?SGWID=5-10042-820-0-0" math)
				("http://jeremykun.com/feed/" math CS programming)
				("https://feeds.feedburner.com/theendeavour" math CS programming)
				("http://blog.computationalcomplexity.org/rss.xml" math CS)
				("https://cloud.google.com/blog/big-data/feed.xml" CS programming)
				("http://www.springer.com/computer?SGWID=5-146-820-0-0" CS)
				("http://www.springer.com/statistics?SGWID=5-10128-820-0-0" statistics)
				("http://lambda-the-ultimate.org/rss.xml" PLT)
				("http://www.bunniestudios.com/blog/?feed=rss2" hardware)
				("http://jods.mitpress.mit.edu/data/rss.xml" design)
				("http://scitation.aip.org/rss/content/aip/journal/jap/latestarticles?fmt=rss" physics)
				("http://www.springer.com/physics?SGWID=5-10100-820-0-0" physics)
				("http://feeds.nature.com/nmat/rss/current?format=xml" materials)
				("http://onlinelibrary.wiley.com/rss/journal/10.1002/ (ISSN) 1521-4095" materials)
				("http://www.springer.com/materials?SGWID=5-10041-820-0-0" materials)
				("http://www.designnews.com/rss_simple.asp" mechanical)
				("http://www.springer.com/engineering?SGWID=5-175-820-0-0" engineering)
				("http://ijr.sagepub.com/rss/current.xml" robotics)
				("http://onlinelibrary.wiley.com/rss/journal/10.1002/ (ISSN) 1097-0363" fluids)
				("http://journals.cambridge.org/data/rss/aggregated/feed_31745_rss.xml" fluids)
				("http://eprint.iacr.org/rss/" crypto)
				("https://arxiv.org/rss/cs" CS)
				("https://arxiv.org/rss/math.AT" math)
				("https://arxiv.org/rss/math.DS" math)
				("https://arxiv.org/rss/math.LO" math)
				("https://arxiv.org/rss/math.OC" math)
				("https://arxiv.org/rss/math.RA" math)
				("https://arxiv.org/rss/math.ST" math)
				("https://arxiv.org/rss/stat" math)
				("https://arxiv.org/rss/math.NT" math)
				("https://arxiv.org/rss/math.GR" math)
				("https://arxiv.org/rss/math.CO" math)
				("https://arxiv.org/rss/math.IT" math)
				("https://arxiv.org/rss/nlin.CD" math)
				("feed://lemire.me/blog/feed/" CS)
				("feed:https://blog.regehr.org/feed" CS programming)
				("https://johncarlosbaez.wordpress.com/feed/" math)))

;; ("http://phys.org/rss-feed/" physics)
;; ("http://aviationweek.com/rss.xml" aerospace)
;; ("https://arxiv.org/rss/math.AP" math)
;; ("http://www.journals.elsevier.com/engineering-geology/rss/" geology)
;; ("http://www.springer.com/earth+sciences+and+geography/environmental+science+%26+engineering/rssfeed?5-1733413-820-0-0" geology)
;; ("http://www.springer.com/earth+sciences+and+geography?SGWID=5-10006-820-0-0" geology)
;; ("http://www.springer.com/east/home/biomed/rssfeed?SGWID=5-124-820-0-0" biomedical)
;; ("http://www.springer.com/medicine?SGWID=5-10054-820-0-0" medicine)
;; ("http://www.springer.com/chemistry?SGWID=5-135-820-0-0" chemistry)

(provide 'setup-elfeed)
